### ISSUE TITLE
Broken endpoint

### ISSUE THREAD

**Issue by bodeby** [Educado-App/educado-frontend#10]
**Issue Description**

I am encountering a broken endpoint in our microservice mock.

**Steps to Reproduce**

1. Start the microservice mock locally.
2. Send a GET request to the endpoint `/api/resource`.
3. Observe the response.

**Expected Behavior**

I expected to receive a 200 OK response with mock data for the `/api/resource` endpoint.

**Actual Behavior**

Instead, I received a 404 Not Found response with the following message: "Endpoint not found."

**Additional Information**

- **Environment:** Local development environment
- **Screenshots:** N/A
- **Logs:** N/A

**Comment by Laskiri** [comment]
don't see how this is relevant anymore as there is no resources path on the server :) I'm closing it don't @ me
