### ISSUE TITLE
[Web - Create New course] Publish course

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#101]
As a content creator, I want to finish a course that was created

Problem:
- Unable to finalize a course that has been created
- Don't have the review course page, so it is not possible to follow to the next page where should have a publish button 
- When clicking "Revisar curso" to review, it appears a message to confirm if I want to leave the page 
- When clicking "Salvar como rascunho" to save as a draft, it appears the same message. The ideal it's to have a dialog so the user confirm the action and, when confirming, takes the user to the home page with a notification that was successfully saved as a draft 
- While we don't have a preview functionality, move the publish button to the section page. 

![Image](https://github.com/user-attachments/assets/a6917df1-d17b-4fcd-a811-8584ed578078)

Acceptance Criteria:
- Change "review course" Button to "publish course" in the section creation page (or course review page if implemented), that allows to set the status of a course to be published.
- When editing a published course, there should just be 1 button to save the changes. 
- When a course is published the save button says "save changes" instead of "save as draft"
- On the courses page a published course is labeled as published
- When logging onto the app after publishing a course it shows up under explore courses

**Comment by iarandrd** [comment]
Publish course button: "Publicar Curso"

**Comment by magnusklundgren** [comment]
Change name to publish changes after a course is published

**Comment by iarandrd** [comment]
"Publicar Edições"

**Comment by magnusklundgren** [comment]
### User Tests:
**Scenario 1: Course Publication**

Steps:

- User creates a new course.
- User completes the course creation process.
- User clicks the "Publish Course" button.

Expected Outcomes:

- The course's status is updated to "Published".
- The user is notified that the course has been published successfully.
- The published course appears in the "Explore Courses" section of the app.

**Scenario 2: Course Editing and Saving**

Steps:

- User edits a published course.
- User clicks the "Publish changes" button.

Expected Outcomes:

- The changes made to the published course are saved.
- The course's status remains "Published".

**Scenario 3: Course Status on Courses Page**

Steps:

- User views the courses page.

Expected Outcomes:

- Published courses are clearly labeled as "Published".
- The user can easily identify published courses from unpublished courses.

**Scenario 4: Course Visibility After Publishing**

Steps:

- User logs out of the app.
- User logs back in to the app.

Expected Outcomes:

- The user's published course appears in the "Explore Courses" section of the app.
- Other users can also view and access the published course.
