### ISSUE TITLE
[Web - Approval] Submit forms to approval

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#108]
As a freelance content creator, I want to be able to send my specific information to submit my request to be a new user

Problem: It's not possible to move forward from the register page if I don't have instutional email, nothing happens when clicking "Cadastrar" button. 

Solution: 
- It should move to "Information" page as figma to fill and send to approval
- Add a dialog to the user confirm the action and send
- Add a confirmation dialog informing that the request was sent  

Figma: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=1664-3152&t=IJrLpGC63r9NcvmY-4

**Comment by MBryder** [comment]
Acceptance criteria:


1. Move to "Information" Page for Users Without Institutional Email:

Given that the user does not have an institutional email,
When a user without an institutional email clicks the "Cadastrar" button,
Then the system should successfully redirect to the "Information" page, as shown in the Figma design, allowing them to fill out their personal details and submit their request for approval.


2. Confirmation Dialog Upon Submission:

Given that the user has filled out all the required fields on the "Information" page,
When the user clicks the "Enviar para análise" button,
Then a confirmation dialog should appear asking the user to confirm their action (e.g., "Are you sure you want to submit your request?").


3. Request Sent Confirmation:

Given that the user confirms the submission from the dialog,
When the submission is successfully sent for approval,
Then a confirmation dialog should notify the user that the request has been successfully sent and is pending review (e.g., "Your request has been successfully submitted for approval").


4. Error Handling for Missing Information:

Given that there are missing required fields (except institutional email) or a network issue occurs during submission,
When the user clicks the "Cadastrar" or "Enviar para análise" button,
Then the system should display a clear error message instructing the user to fix the issue (e.g., "Please fill out all required fields.").
