### ISSUE TITLE
[Web - Approval] Analysis email

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#110]
As a freelance content creator, I would like to receive an email if my registration request has been denied or approved

- If denied, email should contain explanation and a link to try again 
- If approved, email should contain a link to the login page

**Comment by Lowkee1g** [comment]
###  - Acceptance Criteria:
        - The system must send an email notification when a registration request is either approved or denied.
        - If the registration request is denied, the email should include a clear explanation of the reason and a link to try again.
        - If the registration request is approved, the email should include a link to the login page.
        - The email must be sent promptly after the registration decision is made.
        - (The email content should match the UI design and follow the app's tone and style guidelines.) Have some text in portouges → contact Iara

**Comment by davidfraenkel** [comment]
@iarandrd 
If denied, email should contain explanation and a link to try again
If approved, email should contain a link to the login page

Are there any official links to the page otherwise we cant put a link into the email.
Otherwise we can add a dummy link :)
