### ISSUE TITLE
[Web - Home] View rates 

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#113]
As a content creator, I want to see the rate and the feedbacks the students have given to my course after finishing it

Define how and where the user should view this information.

Add new students feedbacks in the activities 

Linked with mobile requirement for feedback

**Comment by Lowkee1g** [comment]
- [ ] Content creators can view average ratings (e.g., 4.5/5) and individual student feedback in a "Course Feedback" tab within the course dashboard.
- [ ] Includes student's name (or anonymous), date, rating, and comments.
- [ ] Shows rating distribution and highlights common feedback themes.
