### ISSUE TITLE
[Web - Create New Course] Course preview

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#115]
Problem: Content creators currently lack a way to visually preview how their course will appear to students before publishing. Without a preview, creators might miss layout issues or other details that could affect the course's clarity and student experience.

Goal: Enable content creators to review their course in a simulated app view, mirroring the student experience. This feature allows creators to make final adjustments with confidence before publishing

Scope:
- Add a "Review Course" step in the course creation flow.
- Display the course in a preview format that mimics the app’s student view, including both course details and section structure.
- Allow navigation between sections of the course within the preview to ensure each component is accurately displayed.
- Allow creators to return to earlier sections for adjustments if they notice issues during the preview.

Risks and Unknowns:
- Complexity of accurately mirroring the app’s exact student interface on the web platform

Success Criteria:
- Content creators can access a preview that closely resembles the app’s student view.
- The preview displays all essential course details and section navigation accurately.
- "Save as Draft" and "Publish" options function correctly, allowing creators to finalize their course at their discretion.

Figma: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=3101-11508&t=Ye9AmGP5p93LiLc6-4

**Comment by BabaWolo** [comment]
@iarandrd 

There's a minor issue I'd like your input on.

The Figma, web, and mobile designs are not fully aligned. (See images below)
We've tried to match the final implementation as closely as possible to the Figma design, but there are still some differences in the outcome.

Do you think the current state is acceptable, or how would you suggest we address this?

![Image](https://github.com/user-attachments/assets/4900b0f8-7adc-4a92-8627-2c73acb07463)
![Image](https://github.com/user-attachments/assets/e0c8b3f1-8c35-4f65-aba5-ad1baaafbd50)
![Image](https://github.com/user-attachments/assets/35056942-e8fd-4d30-8037-66f2340d8a45)

**Comment by iarandrd** [comment]
The Figma design is probability outdated with how we have implemented on the app. Keep the implemented design, please, especially the colors and fonts
