### ISSUE TITLE
[Web - Create New Course] Text editing experience

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#118]
As a content creator, when creating a textual lecture I want to have a more comprehensive text editing experience

Create a "rich-text" experience 

Figma: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=3073-10469&t=Ye9AmGP5p93LiLc6-4

**Comment by Kasper-Sie** [comment]
1. Comprehensive Text Formatting Tools

The rich-text editor should offer standard formatting options, including:
Bold, italic, underline, and strikethrough.
Font size and style selection.
Text color and background color options.
Alignment options (left, center, right, justify).
Bullet points, numbered lists, and checklists.
Indentation controls (increase/decrease indent).

2. Media Embedding

Users should be able to embed various media types directly into the editor:
Images: Upload or link images with resizing and positioning options.
Videos: Embed videos from URLs (e.g., YouTube, Vimeo) with playback inside the editor.
Files: Allow attachments like PDFs or documents within the text.

3. Hyperlink and Anchor Tags

Users should be able to:
Add hyperlinks to external sources or internal pages.
Create anchor tags to link different sections of the lecture for easy navigation.

4. Code Snippets

Provide support for inserting code snippets with syntax highlighting for multiple programming languages.

5. Tables

Users should be able to create tables, including:
Row and column insertion or deletion.
Merging and splitting cells.
Formatting of table borders, background colors, and alignment.

6. Heading and Structure Controls

Users should be able to create and manage text structure with heading levels:
Heading 1, Heading 2, Heading 3, etc.
Block quotes for emphasizing important sections.

7. Undo/Redo and History

The editor must have undo and redo functionality for text editing.
A version history feature should allow users to revert to previous versions of the lecture.

8. Keyboard Shortcuts

Common keyboard shortcuts should be supported for bold (Ctrl+B), italic (Ctrl+I), underline (Ctrl+U), and other actions to enhance productivity.

9. Drag and Drop

Users should be able to drag and drop files, images, or videos into the editor for quick embedding.

10. WYSIWYG (What You See Is What You Get)

The editor should display the content in a form that closely resembles the final output.
Changes should be reflected immediately within the editor to give the user a real-time preview.

11. Preview Mode

Users should have a dedicated "Preview Mode" button to toggle between editing and viewing the final version of their text.

12. Responsive Design

The rich-text editor must work across all screen sizes (desktop, tablet, mobile) without losing functionality or usability.

13. Autosave

Changes made in the editor should be autosaved periodically to prevent loss of content.
The user should be notified if the content is autosaved or unsaved.

**Comment by MBryder** [comment]
Acceptance Criteria for Rich-Text Experience:


1. Rich-Text Editor Integration:

Given that the content creator is adding a textual lecture,
When the user selects the "Texto Estilizado" (Styled Text) option,
Then the system should present a rich-text editor interface that includes various formatting tools (bold, italic, underline, font size, text alignment, lists, etc.).


2. Text Formatting Options:

Given that the user is in the rich-text editor,
When the user clicks on any text formatting buttons (e.g., bold, italics, heading levels, lists),
Then the selected formatting should immediately be applied to the highlighted text in the editor.


3. Insert Media and Hyperlinks:

Given that the user is using the rich-text editor,
When the user wants to insert media (e.g., images or videos) or hyperlinks,
Then the editor should allow them to insert and format media elements or hyperlinks within the text.


4. Preview of Formatted Content:

Given that the user has formatted the text using the rich-text editor,
When the user clicks on a "Preview" button (or similar),
Then the system should display a preview of the lecture content as it would appear to end-users, showing all the applied formatting.


5. Save and Continue Drafting:

Given that the user has started drafting the textual lecture in the rich-text editor,
When the user clicks the "Salvar como Rascunho" (Save as Draft) button,
Then the system should save the current state of the text and formatting, allowing the user to continue editing later.


6. Error Handling for Incomplete Content:

Given that the user tries to save or submit the lecture without entering the required information (e.g., title or text),
When the user clicks "Adicionar Aula" (Add Lecture) or "Enviar para Análise" (Submit for Review),
Then the system should display an error message (e.g., "Please complete all required fields before submission").
