### ISSUE TITLE
[Web - Profile] Delete account

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#121]
As a content creator, I want to have the ability to delete my account:

- The button exists and a confirmation pop-up appears, but the functionality of the confirm button within isn't functioning. 
- Pop-up box style needs to be aligned with Figma: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=2839-5951&t=JW5nnhDtGHlIs30y-4

**Comment by Laskiri** [comment]
Check out this issue: https://github.com/Educado-App/educado-frontend/issues/37
By fixing it all you need to do is attach the service function to the delete button on click

**Comment by Laskiri** [comment]
> Check out this issue: [#37](https://github.com/Educado-App/educado-frontend/issues/37) By fixing it all you need to do is attach the service function to the delete button on click

Also remember to attach the auth token for the axios request, since the delete route uses the requireLogin middleware :D!
