### ISSUE TITLE
[Web - Certificate] Empty state

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#127]
As a content creator, I want to have a empty state view of the certificate page if I don’t have certificates yet

**Comment by LazarShockX** [comment]
**Acceptance Criteria:**

**1. Empty State Display:**
Given a content creator who has no certificates,
When they navigate to the "Certificates" page,
Then an empty state view should be displayed, indicating that no certificates are available yet.

**2. Empty State Messaging:**
Given a content creator without certificates,
When they see the empty state view,
Then the view should include the following elements:
A message such as "You don't have any certificates yet."
A brief explanation or encouragement to earn certificates (e.g., "Start creating more content to earn certificates!").

**3. Placeholder Graphics (Optional):**
Given a content creator without certificates,
When they view the empty state,
Then a visually appealing placeholder graphic (e.g., an icon or illustration) should be displayed to emphasize the empty state.

**4. Call to Action (Optional):**
Given a content creator without certificates,
When the empty state is displayed,
Then there should be a prominent call-to-action (CTA) button that encourages the content creator to take the next steps, such as:
"Create new content"
"Explore certificate opportunities"
When the CTA button is clicked,
Then the content creator should be redirected to a relevant section of the platform (e.g., content creation page or help page for earning certificates).

**5. User with Certificates:**
Given a content creator who has earned certificates,
When they navigate to the "Certificates" page,
Then the certificates they have earned should be displayed in a list or grid view.
Then the empty state view should no longer appear.

**6. Consistent Design:**
Given the empty state view,
When it is displayed,
Then the design (e.g., colors, fonts, spacing) should be consistent with the rest of the platform’s UI to provide a seamless experience.

**7. Responsiveness:**
Given a content creator using any device (desktop, tablet, or mobile),
When the empty state view is displayed,
Then it should be fully responsive and adjust to different screen sizes without losing readability or functionality.
