### ISSUE TITLE
[Web Home] As a content creator, I want to view when I don't have an active course (empty state) and be directed to the creation environment

### ISSUE THREAD

**Issue by JackSMunn** [Educado-App/educado-frontend#16]
- [ ] When a content creator has no active courses they should see an empty state screen
- [ ] On the empty state screen, there should be a prominent action button or link labeled "Create Course" or a similar term that directs the content creator to the course creation environment
- [ ] The empty state screen should display a clear message indicating that the content creator does not have any created courses.
- [ ] Verify that clicking on the "Create Course" button/link successfully navigates the content creator to the course creation environment.
- [ ] Once the content creator has created a course or navigated away from the empty state, the application's navigation should remain consistent with the user's role and access rights.

**Comment by Laskiri** [comment]
this is resolved
