### ISSUE TITLE
[Web Home] As a content creator, I want to view my created courses and their status

### ISSUE THREAD

**Issue by JackSMunn** [Educado-App/educado-frontend#17]
- [ ] On the web application's home page, a content creator should see a list of their created courses.
- [ ] Each course in the list should display its status, which could include indicators, this COULD BE "Published," "Draft," , "hidden".
- [ ] For each course, display the course name and relevant details (e.g., creation date, last modified date) to help content creators identify their courses.
-        [ ] cover (image)
-        [ ] name
-        [ ] #subscribed
-        [ ] rating (out of 5 stars) 
-        [ ] Last modified date (not sure if needed)
- [ ] Courses in the list should be clickable, allowing content creators to navigate to the respective course details or editing pages.

**Comment by Laskiri** [comment]
im closing this, already resolved
