### ISSUE TITLE
[Web - Home] Feedbacks

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#206]
Problem Statement: Content creators currently lack visibility into the feedback students provide after completing their courses. Without this information, it’s challenging for creators to identify areas of improvement or understand what aspects of the course are resonating well with students.

Goal: Provide content creators with a feature to view feedback comments from students who have completed their courses. This will help them make data-driven improvements and maintain high-quality content.

Scope:
- Display student comments linked to specific courses that they completed.
- Include a section in the course management interface or a separate "Feedback" tab for easier access.
- Details Displayed: Student comment text with Rating
- Include the new comments on Activities (Atividades) section on the dashboard 
- Notification: Display a notification or badge when new feedback is received.

Solution Ideas (can check with the designer):
- Add a dedicated "Feedback" section within each course's details page 

Risks and Unknowns:
- Volume of feedback might overwhelm content creators if not properly sorted or filtered.
- Ensuring anonymity or privacy for student feedback while displaying actionable insights.
- Handling inappropriate or offensive comments in feedback.
- Need to balance feedback details with simplicity to avoid overwhelming the user interface.

Success Criteria:
- Content creators can access feedback comments for their courses in a clear and organized manner.
- The feedback includes essential details such as comment text, timestamp, and optionally ratings.
- Creators can easily filter or sort feedback for better navigation.

Considerations:
- Provide feedback trends (e.g., recurring themes or keywords) to help creators focus on actionable improvements.
- Ensure the feature scales well as the number of courses and feedback increases.

**Comment by luisaleaol** [comment]
Hey! Here's the link for this section. Let me know if you have any concerns :)
