### ISSUE TITLE
[Team Offline Delete Account] dependency on working login and account page

### ISSUE THREAD

**Issue by sofiiagran** [Educado-App/educado-frontend#21]
## Issue Description

I want to push the delete account functionality, but right now there is no working login and account page, because of this I cannot push the delete account button. However, I have used the onboarding group branch, to check that the button works with the front-end UI as well as fetching the currently logged-in user's id, and everything works.

## Expected Behavior

Delete user button will be at the account page, and it will delete the current logged in user

## Actual Behavior

It works, but cannot be pushed to dev before logged in page and account page is pushed to dev

**Comment by Jatewo** [comment]
@sofiiagran Why can it not go to dev? I know it cannot really be used before we're able to login but that shouldn't stop you.
