### ISSUE TITLE
Not able to login or register on the web page

### ISSUE THREAD

**Issue by Jatewo** [Educado-App/educado-frontend#22]
## Issue Description

I am not able to login or register on the web page. This means we cannot access other pages and cannot use anything where a login is required.

## Steps to Reproduce

1. Run the frontend and backend
2. Access any existing page on the web (you'll be sent to login)
3. Attempt to login or register

## Expected Behavior

Successful registration/login

## Actual Behavior

Nothing happens

## Additional Information

- **Environment**: Chrome, MacOS
- **Screenshots**: 
<img width="1691" alt="image" src="https://github.com/Educado-App/educado-frontend/assets/92511194/7749b76c-7d9e-4f9e-9db3-8f0adbd4fcd2">
<img width="1114" alt="image" src="https://github.com/Educado-App/educado-frontend/assets/92511194/812cd303-3ad2-4c23-8899-50e135e78019">

**Comment by Laskiri** [comment]
this is not an issue anymore
