### ISSUE TITLE
Updated to account.services for User rework

### ISSUE THREAD

**Issue by Jatewo** [Educado-App/educado-frontend#37]
## Issue Description

account.services uses an old URL as of pull request #36. It needs to be updated to use the new user model (as soon as this has been merged).

## Steps to Reproduce

N/A

## Expected Behavior

Sends request for account deletion to `/api/users/:id` as a `DELETE` request.

## Actual Behavior

Sends a `DELETE` request to `/profile/delete/:id`.

## Additional Information

This is only to be implemented after the review on Nov 6 when the new User rework has been merged.

**Comment by Laskiri** [comment]
Currently account.service uses `${BACKEND_URL}/api/creators/${creatorId}`); endpoint, but no creators route exists in the backend, so I'm updating the deleteUser service function to properly utilize the existing backend route.

**Comment by MartinJenzen** [comment]
`DELETE` request fixed in PR #121
