### ISSUE TITLE
Can't sign up and login as a content crateror 

### ISSUE THREAD

**Issue by magnemo** [Educado-App/educado-frontend#43]
## Issue Description
Can't sign up and login as a content crateror 

## Steps to Reproduce

1. Go to the login page or sign up page 
2. fill in the fieldes 
3. click create or login 

## Expected Behavior

succesful login or sign up

## Actual Behavior

axios error 

## Additional Information

- **Environment**: Browser

**Comment by MortenMunk** [comment]
This is fixed now ☕
