### ISSUE TITLE
[Web - Approval] As a content creator from a partner institution, I want to have the ability to register directly as a new user, just with the basic information, so that I can log in to the platform going forward

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#93]
Description:
Currently, it is necessary to wait for approval even with a corporate email

Solution Proposal:
Define business rule for the approval flow, how the Admin Page should work, who are the admin and how they can edit the users permissions to set who else can be admin. 

Bug Priority Number: 5

**Comment by Thomass1412** [comment]
Things that needs to be done:
1. When you cancel and request a new code, the old one should be invalid and the new one should be the correct code
2. The code should have an expiration time 
3. The email text recieved should be correct according to Iara 
4. The color of the pop-up component should be correct according to Iara

**Comment by iarandrd** [comment]
Let's follow this figma template for dialogs: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=5217-2723&t=5CDNvsMu7rXdvHGs-4

Remember that this is only a template, so the text needs to be changed.

**Comment by magnusklundgren** [comment]
### User Tests:
**Scenario 1: Email Verification and Approval**

Steps:

- User enters an institution email address.
- User requests a verification code.
- User enters the received verification code.

Expected Outcomes:


- The user is prompted to enter a verification code.
- The verification code is sent to the specified corporate email address.
- The user can successfully verify their email and proceed to the next step.

**Scenario 2: Code Expiration and Resend**

Steps:

- User requests a verification code.
- User fails to enter the code within the expiration time.
- User requests a new verification code.

Expected Outcomes:

- The previous verification code is invalidated.
- A new verification code is sent to the user's email.
- The user can successfully verify their email using the new code.

**Scenario 3: Normal signup**

Steps:

- User registers with a non-institution email
- User fills out motivation for application
- User submits application

Expected Outcomes:

- The user gets directed to the application page after registering with a non-institution email.
- The user is able to submit an application which is then sent to the admin section of the website.

**Scenario 4: Interrupted signup with non-institution email**

Steps:

- User registers with a non-institution email
- User is redirected to the application page
- User leaves the application page
- User attempts to signup using the same email

Expected Outcomes:

- After registering, the user is redirected to the application page.
- After leaving the page and signing up again the user should once again be redirected to the application page. and able to submit an application
- The application is correctly submitted on the second registration
