### ISSUE TITLE
[Web - Create New Course] Guide through the functionalities

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#99]
As a new user, I would like to have an experience guided through the functionalities

Description:
There are no instructions on how the course should be presented, whether tests are required, minimum and maximum duration

Solution Proposal:
Include an instructions and tips page when creating a new course

Improvement Priority Number: 6

Comments:
This could be considered "new"

**Comment by TueRask** [comment]
Acceptance criteria:

- A new user must be presented with an intuitive guide when creating a course for the first time.
- The guide should walk the user through key functionalities, such as adding course details, uploading content (videos, 
   images, documents), setting tests, and defining course duration.
- This page must include guidelines on:
   The minimum and maximum course duration allowed.
   Whether tests or assessments are mandatory.
- The system should provide a dedicated page or pop-up with instructions for creating courses.
- Ensure that users can easily access this page at any point during the course creation process.
